CREATE SCHEMA IF NOT EXISTS `nghiencuu` DEFAULT CHARACTER SET utf8 ;
USE `nghiencuu` ;


CREATE TABLE IF NOT EXISTS `nghiencuu`.`DETAI` (
  `MaDeTai` INT NOT NULL,
  `Tendetai` VARCHAR(45) NULL,
  `LinhvucNC` VARCHAR(45) NULL,
  PRIMARY KEY (`MaDeTai`))
;


CREATE TABLE IF NOT EXISTS `nghiencuu`.`GIAOVIEN` (
  `MaGV` INT NOT NULL,
  `HoTen` VARCHAR(45) NULL,
  `HocHam` VARCHAR(45) NULL,
  `HocVi` VARCHAR(45) NULL,
  `DETAI_MaDeTai` INT NOT NULL,
  PRIMARY KEY (`MaGV`),
  INDEX `fk_GIAOVIEN_DETAI1_idx` (`DETAI_MaDeTai` ASC) VISIBLE,
  CONSTRAINT `fk_GIAOVIEN_DETAI1`
    FOREIGN KEY (`DETAI_MaDeTai`)
    REFERENCES `nghiencuu`.`DETAI` (`MaDeTai`)
);

CREATE TABLE IF NOT EXISTS `nghiencuu`.`SINHVIEN` (
  `MaSV` INT NOT NULL,
  `HoTen` VARCHAR(45) NULL,
  `Lop` VARCHAR(45) NULL,
  `DETAI_MaDeTai` INT NOT NULL,
  `GIAOVIEN_MaGV` INT NOT NULL,
  PRIMARY KEY (`MaSV`),
  INDEX `fk_SINHVIEN_DETAI_idx` (`DETAI_MaDeTai` ASC) VISIBLE,
  INDEX `fk_SINHVIEN_GIAOVIEN1_idx` (`GIAOVIEN_MaGV` ASC) VISIBLE,
  CONSTRAINT `fk_SINHVIEN_DETAI`
    FOREIGN KEY (`DETAI_MaDeTai`)
    REFERENCES `nghiencuu`.`DETAI` (`MaDeTai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SINHVIEN_GIAOVIEN1`
    FOREIGN KEY (`GIAOVIEN_MaGV`)
    REFERENCES `nghiencuu`.`GIAOVIEN` (`MaGV`)
  );
