CREATE SCHEMA IF NOT EXISTS `db_hanghoa` DEFAULT CHARACTER SET utf8 ;
USE `db_hanghoa` ;

CREATE TABLE IF NOT EXISTS `db_hanghoa`.`MATHANG` (
  `MH` INT NOT NULL AUTO_INCREMENT,
  `TENHANG` VARCHAR(45) NULL,
  `DVT` VARCHAR(45) NULL,
  `SLHC` VARCHAR(45) NULL,
  `GBHT` VARCHAR(45) NULL,
  PRIMARY KEY (`MH`));

CREATE TABLE IF NOT EXISTS `db_hanghoa`.`PHIEUNHAP` (
  `SP` INT NOT NULL,
  `NGAYNHAP` VARCHAR(45) NULL,
  `TNCC` VARCHAR(45) NULL,
  `MATHANG_MH` INT NOT NULL,
  PRIMARY KEY (`SP`),
  INDEX `fk_PHIEUNHAP_MATHANG_idx` (`MATHANG_MH` ASC) VISIBLE,
  CONSTRAINT `fk_PHIEUNHAP_MATHANG`
    FOREIGN KEY (`MATHANG_MH`)
    REFERENCES `db_hanghoa`.`MATHANG` (`MH`)
);

CREATE TABLE IF NOT EXISTS `db_hanghoa`.`HOADONXUAT` (
  `SOHD` INT NOT NULL,
  `NGAYBAN` VARCHAR(45) NULL,
  `TENNGMH` VARCHAR(45) NULL,
  `MATHANG_MH` INT NOT NULL,
  PRIMARY KEY (`SOHD`),
  INDEX `fk_HOADONXUAT_MATHANG1_idx` (`MATHANG_MH` ASC) VISIBLE,
  CONSTRAINT `fk_HOADONXUAT_MATHANG1`
    FOREIGN KEY (`MATHANG_MH`)
    REFERENCES `db_hanghoa`.`MATHANG` (`MH`)
    );




